### PR TITLE
add prefer-standby target_session_attrs

### PR DESCRIPTION
**Pull request by sbashilov**
Add prefer-standby target session attr, which described as

prefer-standby
first try to find a standby server, but if none of the listed hosts is a standby server, try again in any mode

### CODE REVIEW

**Review by jackc — COMMENTED** [review]
As you probably noticed, pgconn's use of the fallback config pattern doesn't fit too well with `prefer-standby`.

Needing to have a `HasPreferStandbyTargetSessionAttr` and `ValidateConnectTargetSessionAttrsPrefferStandby()` s rather inelegant. But in the current architecture I can't think of a better approach.

Long-term it may be that a function that generates the next connect attempt maybe a better approach than a list of `FallbackConfig`.

What do you think of making `HasPreferStandbyTargetSessionAttr` and `ValidateConnectTargetSessionAttrsPrefferStandby()` private? This feature would still be accessible via the connection string, but it would not lock us into this implementation / interface.

**Comment by sbashilov** [comment]
I've fixed typos plus returned old pg error check.

About making `HasPreferStandbyTargetSessionAttr` and `ValidateConnectTargetSessionAttrsPreferStandby` private. I can not do that, because I use them in tests, and tests have different package.
And I can not move them to `internal` because then it will be cycle import

**Comment by jackc** [comment]
I thought a bit more about this. The only reason I wanted to make it private was because the interface was inelegant. It is better for usability and testing if it is public. Maybe there is another interface that makes sense.

What if we changed the meaning of the return value of `ValidateConnect` slightly? Right now any error means the connection is impossible. Instead what if there was a specific sentinel error that could be returned that indicated that the connection is acceptable, but not preferred.

With that change `HasPreferStandbyTargetSessionAttr` would be unnecessary. And it would allow arbitrary acceptable vs. preferred connection logic instead of only duplicating `prefer-standby`.

Not sure of the name for the sentinel error, maybe something like: `ErrNotPreferred`.

**Comment by jackc** [comment]
Okay, I think this is looking pretty good.

But one thing that I'm not sure about is the `config.ValidateConnect = nil` in the try again path. This would mean that it is not safe to use the same `ConnConfig` multiple times.

Also, it is possible for server state to change in the brief window between the first connection and the second connection. I think it would be better to preserve `config.ValidateConnect` and have the try again path ignore `NotPreferredError`.

**Comment by sbashilov** [comment]
But this will require changes in `connect` function, since it closes connection if `ValidateConnect` returns error
`err := config.ValidateConnect(ctx, pgConn)
				if err != nil {
					pgConn.conn.Close()
					return nil, &connectError{config: config, msg: "ValidateConnect failed", err: err}
				}`
And now `connect ` function does not know is it try again path or not.
That's why I change `config.ValidateConnect` so it would try again in `any` mode

**Comment by jackc** [comment]
> But this will require changes in connect function

That is correct. It either needs an argument telling it if it is the try again path or it needs to never close the connection on `NotPreferredError` and have the caller responsible for the close of the non-fatal error (probably the argument is better).

It is a little awkward, but the alternative is mutating the config and having a window in which the validation check is not performed. IMO this is unexpected at best, incorrect at worst.

**Comment by sbashilov** [comment]
Yeah, I agree that additional argument would be better

**Comment by jackc** [comment]
👍

**Pull request merged**
