### PR TITLE
Validate all addresses resolved from hostname

### PR DESCRIPTION
**Pull request by furdarius**
`LookupFunc` added to config, so custom resolver can be used.

`fallbackConfigs` used to iterate over resolved addrs.

fix: #5

### CODE REVIEW

**Comment by furdarius** [comment]
@jackc what do you think about this PR?

**Comment by jackc** [comment]
Sorry, somehow I unwatched my own project so I didn't see this until you pinged me...

This PR is actually combining two concerns.

1. Allowing a custom resolver
2. Expanding a host name into multiple addresses

There are some subtle edge cases with each.

The custom resolver appears to only be called by `expandWithIPs` and that appends to the fallbacks. That means that the host name will be dialed with the default resolver before the custom resolver is tried. Presumably that is not desired.

The other issue is what happens when DNS changes. A Config could be used for a long time in a server process. and it could be stuck never seeing the updated DNS.

For both concerns to work properly, the DNS resolution (and expansion to multiple IPs) has to occur at dial time not parse config time.

**Comment by furdarius** [comment]
Hm, any kind of resolving and dealing occurs only inside `ConnectConfig` func.
So, while the connection, received from `ConnectConfig`, is alive - we don't care about DNS changes, cuz we just use this connection to work with DB.

But, in case of connection is broken we apparently try to reconnect, so we call `ConnectConfig` again - this leads to new DNS resolving (if DNS records was updated - we will receive valid addrs). 

> The custom resolver appears to only be called by expandWithIPs and that appends to the fallbacks. That means that the hostname will be dialed with the default resolver before the custom resolver is tried.

I don't see any calls of `DialFunc` before `expandWithIPs`. A single call of `DialFunc` is inside `connect` (https://github.com/furdarius/pgconn/blob/resolve-hostnames-into-addrs/pgconn.go#L201) and it occurs only after hostnames resolved. 

Maybe I got you wrong.

**Comment by jackc** [comment]
Wow... I really shouldn't review PRs when I'm tired... For some reason I thought the changes to `ConnectConfig` were in `ParseConfig` and thought that `expandWithIPs` was appending to the existing fallbacks instead of creating a whole new list. Now that I'm looking at it again I see I was wrong on both accounts.

LGTM.

**Pull request merged**
