### PR TITLE
Fix: setting krbspn and krbsrvname didn't work

### PR DESCRIPTION
**Pull request by Sireax**
I tried to connect to postgres using kerberos, but setting url parameters krbsrvname and krbspn did'n change anything. Now it is working

See https://github.com/otan/gopgkrb5/issues/1

### CODE REVIEW

**Review by otan — COMMENTED** [review]
interesting, i got this to work with https://github.com/otan/gss_test/blob/main/main.go

i think this might've been my fault for adding these two lines here: https://github.com/jackc/pgconn/blob/9bb49f990f1e563b88fc0772a6a928b14ebd19f0/config.go#L260-L261; can you delete them and try again?

**Comment by otan** [comment]
(https://github.com/jackc/pgconn/pull/111 would be the commit)

**Comment by otan** [comment]
#111 is the alternative; i'll let @jackc decide!

**Comment by Sireax** [comment]
@otan yeah, I also tried just to remove krbspn and krbsrvname from notRuntimeParams, but then its just passed to postgres connection url and another error is raised

**Comment by otan** [comment]
right, yeah i remember now - i did it the way that is in this PR, then switched it sometime but must've forgotten to test it.
thanks for submitting this fix! the lines roughly line up with

```
github.com/otan-cockroach/pgconn v1.11.1-0.20220412042850-fc6177cc0f0f
```

so sorry again

**Comment by otan** [comment]
sorry for the earlier comment, i.misspoke!

>  I also tried just to remove krbspn and krbsrvname from notRuntimeParams, but then its just passed to postgres connection url and another error is raised

ah, that worked with cockroachdb! no worries, this seems better.

**Comment by otan** [comment]
@jackc do you mind pushing a release for this / pgx? thanks!

**Comment by otan** [comment]
Hmm it gives the same functionality as lib%pq atm. That seems like an additional feature.

**Comment by jackc** [comment]
@otan I tagged new releases today.

**Pull request merged**
