### PR TITLE
Add Config.Copy() method that returns a smart copy of the config.

### PR DESCRIPTION
**Pull request by georgysavva**
This is the first step to provide smart config copy for `pgx.Conn` as discussed here: https://github.com/jackc/pgx/issues/752.
In order to continue implementing this feature in `pgx`, after this PR is merged, `pgx` should start using `pgconn` version that contains this change.

### CODE REVIEW

**Comment by jackc** [comment]
Do we need to pull in that deepcopy dependency? I would hope that it would be possible to duplicate the struct then manually deep copy the necessary parts.

Also, I'm worried that deepcopy could have unintended consequences for the tls.Config. It has some private fields. It looks like tls.Config provides a Clone() method -- though it is documented as a shallow clone. And according to the docs it is not supposed to be modified after initial use. So even with that I'm not sure if it is safe if someone changes the tls.Config.

I think that this method needs to document what fields cannot be changed (such as tls.Config).

**Comment by georgysavva** [comment]
Sure. Let's to it this way.

**Comment by georgysavva** [comment]
Please ping me when you release the new version of `pgconn` with this change. So I could start working on the `pgx`

**Comment by jackc** [comment]
I usually tag releases for pgx, pgconn, and other associated projects together. You can update go.mod in pgx to point to this specific commit of pgconn.

**Comment by georgysavva** [comment]
Got it, thanks.

**Pull request merged**
