### PR TITLE
Support parsing empty hosts in config

### LINKED ISSUE #19: ParseConfig can't handle empty hostnames
When using `pgconn.ParseConfig` on a connection string that doesn't specify a hostname, such as `postgresql://root@:5432/postgres`, `pgconn.ParseConfig` produces a config with a host of `/tmp`.

This appears to be because the default host is not overwritten, since the parsed host is not stored if it is empty: https://github.com/jackc/pgconn/blob/32350bd1dc3288aa22f271f87065741da0a1bdb8/config.go#L367.

Not sure if this is an unintentional limitation, but these hostname-less connection strings worked in older versions of `pgx` and generally works when using the Go network libraries, so it would be nice to support it.

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Fixes #19

### CODE REVIEW

**Comment by jackc** [comment]
The new test for DSN with empty host is failing... but it appears to be because that is not how PostgreSQL handles empty values. See https://www.postgresql.org/docs/current/libpq-connect.html#id-1.7.3.8.3.5

**Comment by johanbrandhorst** [comment]
It does appear that way. Should we return an error for empty hosts or do you want to handle it by parsing it into "localhost"? I think the latter might be useful because I'm pretty sure the go standard library sometimes returns an empty host, but I can understand if we want to keep the libpq behaviour.

**Comment by jackc** [comment]
I'd like to match libpq.

**Comment by johanbrandhorst** [comment]
> The default behavior when host is not specified, or is empty, is to connect to a Unix-domain socket in /tmp (or whatever socket directory was specified when PostgreSQL was built). On machines without Unix-domain sockets, the default is to connect to localhost.
There are no examples of an empty hostname with a valid port, so I guess the current behaviour is correct - as long as the hostname part of the host is empty, the whole host should be discarded and default to `/tmp`. I will update the issue and close this PR.

**Pull request closed without merging**
